In [2]:
import numpy as np
arr=np.arange(2,50,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


In [8]:
a=np.array([int(input()) for i in range(5)])
b=np.array([int(input()) for i in range(5)])
print(np.sort(np.concatenate((a,b))))


4
5
7
1
2
3
8
9
10
0
[ 0  1  2  3  4  5  7  8  9 10]


In [9]:
arr=np.array([3,5,2,1,5,6,3])
print(arr.ndim)
print(arr.size)

1
7


In [12]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.vstack(a))
print(np.hstack(a))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [14]:
a=np.arange(1,10)
print(np.unique(a,return_counts=True))

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([1, 1, 1, 1, 1, 1, 1, 1, 1]))
